Feature/pn 3594
pagopa/pn-progression-sensor pull request #8
Opened 2023-01-25 18:10 UTC by FeliceMente

2023-01-26 15:34 UTC, fdammassa requested changes

2023-01-26 15:34 UTC, fdammassa commented on functions/slaViolationChecker/src/app/lib/kinesis.js
> +  const allowedTables = ["pn-ProgressionSensorData"];
Meglio creare un file con una costante con questo valore così da riusarla anche nel modulo dove scrivi su DynamoDb.

2023-01-26 17:45 UTC, fdammassa requested changes

2023-01-26 17:45 UTC, fdammassa commented on functions/slaViolationChecker/src/app/lib/eventMapper.js
> +  if (this.checkRemovedByTTL(event)) {
Così facendo non stai cancellando mai le SLA violation

2023-01-27 08:12 UTC, FeliceMente commented on functions/slaViolationChecker/src/app/lib/dynamoDB.js
> +      relatedEntityId: event.relatedEntityId,
ok: leggo da event.relatedEntityId e scrivo in sla_relatedEntityId

2023-01-27 08:16 UTC, FeliceMente commented on functions/slaViolationChecker/src/app/lib/dynamoDB.js
> +      relatedEntityId: event.relatedEntityId,
già dalla maprte di mapping gestirò la cosa la cosa

2023-01-27 08:22 UTC, FeliceMente commented on functions/slaViolationChecker/src/app/lib/kinesis.js
> +  const allowedTables = ["pn-ProgressionSensorData"];
su questo punto ho bisogno di un chiarimento

2023-01-27 08:23 UTC, FeliceMente commented on functions/slaViolationChecker/src/app/lib/eventMapper.js
> +  if (this.checkRemovedByTTL(event)) {
su questo punto ho bisogno di un chiarimento

2023-01-27 10:09 UTC, FeliceMente commented on functions/slaViolationChecker/src/app/lib/kinesis.js
> +  const allowedTables = ["pn-ProgressionSensorData"];
const allowedTables = [
    /*"pn-ProgressionSensorData"*/ process.env.DYNAMODB_TABLE,
  ];

2023-01-27 10:10 UTC, FeliceMente commented on functions/slaViolationChecker/src/app/lib/eventMapper.js
> +  if (this.checkRemovedByTTL(event)) {
dopo averci ragionato, abbiamo verificato che qui il ramo else non lavorerebbe perché andrebbe a cercare righe da storicizzare che sono state già cancellate da TTL

2023-01-27 10:20 UTC, fdammassa approved these changes

2023-01-27 10:21 UTC, merged